### ISSUE TITLE
Cannot use 'in' operator to search for '*' in undefined

### ISSUE THREAD

**Issue by trackq** [baloise-incubator/spectral-ruleset#17]
The rules don't work with the newest version of Spectral.

### Doesn't work
```shell
$ npx @stoplight/spectral lint \
    --ruleset https://raw.githubusercontent.com/baloise-incubator/spectral-ruleset/main/zalando.yml \
    example/example-openapi.yml

Cannot use 'in' operator to search for '*' in undefined
```

### Does work
```shell
$ npx @stoplight/spectral@5.9.1 lint \
    --ruleset https://raw.githubusercontent.com/baloise-incubator/spectral-ruleset/main/zalando.yml \
    example/example-openapi.yml
OpenAPI 3.x detected

/Users/kaweh/Labs/playground/spectral-ruleset/example/example-openapi.yml
  2:6   error  must-have-info-contact-email   Missing `info.contact.email`.                  info
  2:6   error  must-have-info-contact-name    Missing `info.contact.name`.                   info
  2:6   error  must-have-info-contact-url     Missing `info.contact.url`.                    info
  2:6   error  must-have-info-description     Missing `info.description`.                    info
  2:6   error  must-have-info-x-api-id        Missing `info.x-api-id`.                       info
 14:17  error  must-specify-default-response  Operation does not contain a default response  paths./pet.patch.responses

✖ 6 problems (6 errors, 0 warnings, 0 infos, 0 hints)

```

### Some system info
```shell
$ node --version
v16.1.0

$  npx --version
7.11.2
```

**Comment by leubedane** [comment]
Hey @trackq ,
I tried to update today, but there are still some issues after update. Our tests doesn't work currently. I will try to continue the update the next days.

**Comment by leubedane** [comment]
I tried to update further, but currently our tests don't work. They changed the spectral methods and now I can't get our tests get to work.
Related Issue: https://github.com/stoplightio/spectral/issues/1779

**Comment by dweber019** [comment]
Requested help in discord https://discord.com/channels/841794018173648916/859895506271600670/940940544962621441

**Comment by dweber019** [comment]
Reported issue at https://github.com/stoplightio/spectral/issues/2060, as it seams to be no issue with spectral and nimma.

**Comment by dweber019** [comment]
@trackq stoplight has fixed you bug regarding the error. Never the less there is still a bug in 6.x https://github.com/stoplightio/spectral/issues/2066 which blocks this lib to upgrade.

**Comment by trackq** [comment]
@dweber019 Thank you for following up!

**Comment by dweber019** [comment]
After https://github.com/baloise-incubator/spectral-ruleset/pull/27 is merged spectral 6 works.
