### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by cemo** [baloise-incubator/spectral-ruleset#18]
Hi thanks for sharing your repo. We had been considering similar things and I will be glad that if you can provide some information about:

1. Do you have any schema registry? Where do you store your schemas? 
2. How do you sync open api specs into these central registry?
3. Do you use some specific versioning strategy for applications and openapi specs?  
4. Do you use https://stoplight.io/? 
5. Do you have any checks for builds such as github actions?

**Comment by leubedane** [comment]
Hi @cemo,
I hope I can answer your questions:
1. What do you mean with schema registry? Our REST Apis provide an open api file for the customers. In this open api file there is a schema for the given endpoint provided. We are starting to use Apicurio for our Service registry where you can discover the different services.
2. We upload the open api files to the apicurio service registry via a link to a git revision. So we provide a link to the open api file in git and apicurio downloads the latest version of it.
3. Normal SemVersioning for RESTful APIs.
4. We don´t use stoplight io. We are trying to use apicurio. But we are at the beginning and tool evaluation.
5. Yes we will lint our open api file with our baloise ruleset. This is done in our internal jenkins library. We are using the spectral docker image and install the ruleset in the docker image. With this docker image we will do the linting in a jenkins pipeline.

I hope this answers are useful ;-).

**Comment by cemo** [comment]
Hi @leubedane,

Yes, it helped me a lot. One last question:

1. How do you upload specs to Apicurio? Is there a Kubernetes controller for syncing in the registry?

**Comment by dweber019** [comment]
Hi @cemo 
Yes there is one but under development. https://github.com/Apicurio/apicurio-registry-content-sync-operator

**Comment by cemo** [comment]
I had checked it before but could not see how to update specs in the first place. I need to detect deployments kubernetes and sync to `registry`.

**Comment by dweber019** [comment]
We do it with ArgoCD and by the operator mentioned above.
Just define a yaml like https://github.com/Apicurio/apicurio-registry-content-sync-operator/blob/main/dist/kubernetes/examples/openapi-external-content.yaml and apply it to k8s ;) but maybe it would make more sense so discuss on this repo https://github.com/Apicurio/apicurio-registry-content-sync-operator

**Comment by cemo** [comment]
I had actually opened an issue a few months back ago. We will try to patch as yours. Thank you.
