### ISSUE TITLE
Question about "missing" Zalando rules

### ISSUE THREAD

**Issue by johannesmarx** [baloise-incubator/spectral-ruleset#45]
Hi 👋 ,

I have to admit that I'm currently not too familiar with spectral. Though I'm curious about the rules (e.g. [#112](https://opensource.zalando.com/restful-api-guidelines/#112)) that are marked as "implementation not possible or to complex" in section "[Currently supported rules from the zalando restful-api-guidelines](https://github.com/baloise-incubator/spectral-ruleset?tab=readme-ov-file#currently-supported-rules-from-the-zalando-restful-api-guidelines)".

Could you please elaborate if there are technical reasons (leaving complexity asside) why rules cannot be implemented?

Thanks a lot.

**Comment by dweber019** [comment]
Hi @johannesmarx 

As a fact rule #112 is implemented.
For other rules like #100 or even #103 is hard or even not possible. For example #100 is more of a good practice than a rule, which can be checked. The rule #103 could be sort of checked with a spell checker for english but seams a little overkill to use this with spectral.

But for example #114 could be implemented for sure.

If you like to see a rule implemented, we are happy to review PR's.

**Comment by johannesmarx** [comment]
Hi @dweber019,

thanks a lot for your explanation. I clearly didn't had rules like #100/#103 in mind.
