### ISSUE TITLE
Hyphenated pascal case headers not always wanted

### ISSUE THREAD

**Issue by robert-groensfeld** [baloise-incubator/spectral-ruleset#47]
Rule `should-use-hyphenated-pascal-case-for-header-parameters` conflicts with conventions for trace headers, e.g. [B3 headers](https://github.com/openzipkin/b3-propagation?tab=readme-ov-file#multiple-headers) or [W3C trace context](https://www.w3.org/TR/trace-context/#header-name).

**Comment by dweber019** [comment]
I think for the zalando rule set it's valid to have an error.
Never the less I would suggest to whitelist these headers in the Baloise ruleset.
